# Generated by Django 5.2 on 2025-06-23 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Ponto Turístico')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('tipo', models.CharField(help_text='Ex: Monumento, Parque, Museu, Praia, etc.', max_length=100, verbose_name='Tipo de Ponto Turístico')),
            ],
            options={
                'verbose_name': 'Ponto Turístico',
                'verbose_name_plural': 'Pontos Turísticos',
            },
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_estado_origem', models.CharField(max_length=255, verbose_name='País/Estado de Origem')),
                ('tipo', models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Nacional', max_length=20, verbose_name='Tipo de Turista')),
            ],
            options={
                'verbose_name': 'Turista',
                'verbose_name_plural': 'Turistas',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now_add=True, verbose_name='Horário da Visita')),
                ('origem_turista_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem do Turista (String para relatórios)')),
                ('ponto_visitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='tourism_app.pontoturistico', verbose_name='Ponto Visitado')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='tourism_app.turista', verbose_name='Turista')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-horario'],
            },
        ),
    ]
