# Generated by Django 5.2 on 2025-06-23 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turista',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Turista'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='horario',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horário da Visita'),
        ),
    ]
